apiVersion: v1
kind: Service
metadata:
  name: banking-devops-service
  namespace: banking-devops
  labels:
    app: banking-devops
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: banking-devops
  ports:
  - name: http
    protocol: TCP
    port: 80        # External port
    targetPort: 8000  # Container port
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
